/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"
#include "fsl_pwm.h"
#include "fsl_ctimer.h"
#include "fsl_lpadc.h"
#include "fsl_gpio.h"
#include "fsl_lpuart.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for LPI2C0 */
/* Definition of peripheral ID */
#define LPI2C0_PERIPHERAL LPI2C0
/* Definition of clock source */
#define LPI2C0_CLOCK_FREQ 24000000UL
/* Definition of follower address */
#define LPI2C0_MASTER_SLAVE_ADDRESS 0
/* Definition of peripheral ID */
#define FLEXPWM0_PERIPHERAL FLEXPWM0
/* Definition of submodule 0 ID */
#define FLEXPWM0_MOTORS kPWM_Module_0
/* Definition of clock source of submodule 0 frequency in Hertz */
#define FLEXPWM0_MOTORS_SM_CLK_SOURCE_FREQ_HZ 96000000U
/* Definition of submodule 0 counter clock source frequency in Hertz - FLEXPWM0_MOTORS_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_MOTORS_COUNTER_CLK_SOURCE_FREQ_HZ 96000000U
/* Definition of submodule 0 counter (PWM) frequency in Hertz */
#define FLEXPWM0_MOTORS_COUNTER_FREQ_HZ 20000U
/* Definition of submodule 0 channel A ID */
#define FLEXPWM0_MOTORS_A kPWM_PwmA
/* Definition of submodule 0 channel B ID */
#define FLEXPWM0_MOTORS_B kPWM_PwmB
/* Definition of submodule 0 channel X ID */
#define FLEXPWM0_MOTORS_X kPWM_PwmX
/* Definition of submodule 1 ID */
#define FLEXPWM0_SERVO kPWM_Module_1
/* Definition of clock source of submodule 1 frequency in Hertz */
#define FLEXPWM0_SERVO_SM_CLK_SOURCE_FREQ_HZ 96000000U
/* Definition of submodule 1 counter clock source frequency in Hertz - FLEXPWM0_SERVO_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_SERVO_COUNTER_CLK_SOURCE_FREQ_HZ 1500000U
/* Definition of submodule 1 counter (PWM) frequency in Hertz */
#define FLEXPWM0_SERVO_COUNTER_FREQ_HZ 50U
/* Definition of submodule 1 channel A ID */
#define FLEXPWM0_SERVO_A kPWM_PwmA
/* Definition of submodule 1 channel B ID */
#define FLEXPWM0_SERVO_B kPWM_PwmB
/* Definition of submodule 1 channel X ID */
#define FLEXPWM0_SERVO_X kPWM_PwmX
/* Definition of fault Fault0 ID */
#define FLEXPWM0_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define FLEXPWM0_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define FLEXPWM0_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define FLEXPWM0_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 1UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 1000000000UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of peripheral ID */
#define CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_TICK_FREQ 1UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_TICK_PERIOD 1000000000UL
/* Definition of PWM period channel. */
#define CTIMER1_PWM_PERIOD_CH kCTIMER_Match_0
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Alias for GPIO1 peripheral */
#define GPIO1_GPIO GPIO1
/* Alias for PORT1 */
#define GPIO1_PORT PORT1
/* GPIO1 interrupt vector ID (number). */
#define GPIO1_IRQN GPIO1_IRQn
/* GPIO1 interrupt handler identifier. */
#define GPIO1_IRQHANDLER GPIO1_IRQHandler
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the clock source frequency */
#define LPUART0_CLOCK_SOURCE 12000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpi2c_master_config_t LPI2C0_masterConfig;
extern pwm_config_t FLEXPWM0_MOTORS_config;

extern pwm_signal_param_t FLEXPWM0_MOTORS_pwm_function_config[2];
extern pwm_config_t FLEXPWM0_SERVO_config;

extern pwm_signal_param_t FLEXPWM0_SERVO_pwm_function_config[1];
extern const pwm_fault_input_filter_param_t FLEXPWM0_faultInputFilter_config;
extern const pwm_fault_param_t FLEXPWM0_Fault0_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault1_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault2_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault3_fault_config;
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_config_t CTIMER1_config;
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[1];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[1];
extern const lpuart_config_t LPUART0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
