/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA153
package_id: MCXA153VLH
mcu_data: ksdk2_0
processor_version: 25.09.10
pin_labels:
- {pin_num: '44', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/PWM0_A0/FREQME_CLK_OUT1, label: MOTOR_A_PWM, identifier: MOTOR_A_PWM}
- {pin_num: '42', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, label: SERVO_PWM, identifier: SERVO_PWM}
- {pin_num: '43', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/PWM0_B0, label: MOTOR_B_PWM, identifier: MOTOR_B_PWM}
- {pin_num: '16', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/ADC0_A4/CMP0_IN0, label: ENCODER_A_PHA, identifier: ENCODER_A_PHA;ENCODER_B_PHA}
- {pin_num: '3', pin_signal: P1_9/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3/I3C0_SCL, label: I2C_SCL, identifier: I2C_SCL}
- {pin_num: '2', pin_signal: P1_8/WUU0_IN10/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2/I3C0_SDA, label: I2C_SDA, identifier: I2C_SDA}
- {pin_num: '20', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/CT_INP18/CT1_MAT2/ADC0_A3, label: MESURE_VBAT, identifier: MESURE_VBAT}
- {pin_num: '14', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, label: DEBUG_RX, identifier: DEBUG_RX}
- {pin_num: '15', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/CT_INP17/CT2_MAT1/ADC0_A1, label: DEBUG_TX, identifier: DEBUG_TX}
- {pin_num: '57', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C0_SCL/CT_INP5/CT0_MAT3/ADC0_A17/CMP1_IN3, label: ALERT_LED, identifier: LED_ROUGE;ALERT_LED}
- {pin_num: '58', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C0_SDAS/CT1_MAT0/CT_INP0/ADC0_A18, label: ONOFF_IMX8MP, identifier: ONOFF_IMX8MP}
- {pin_num: '59', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C0_SCLS/CT1_MAT1/CT_INP1/ADC0_A19/CMP0_IN1, label: CMD_CAMERA_LED, identifier: CMD_CAMERA_LED}
- {pin_num: '62', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, label: ONOFF_INT, identifier: ONOFF_INT}
- {pin_num: '63', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, label: ONOFF_KILL, identifier: ONOFF_KILL}
- {pin_num: '17', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/ADC0_A2/CMP1_IN0, label: ENCODER_B_PHA, identifier: ENCODER_B_PHA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: LPI2C0, signal: SCL, pin_signal: P1_9/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3/I3C0_SCL}
  - {pin_num: '2', peripheral: LPI2C0, signal: SDA, pin_signal: P1_8/WUU0_IN10/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2/I3C0_SDA}
  - {pin_num: '16', peripheral: CTIMER0, signal: 'CAPTURE, 0', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/ADC0_A4/CMP0_IN0, identifier: ENCODER_A_PHA}
  - {pin_num: '20', peripheral: ADC0, signal: 'A, 3', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/CT_INP18/CT1_MAT2/ADC0_A3}
  - {pin_num: '44', peripheral: FlexPWM0, signal: 'A, 0', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/PWM0_A0/FREQME_CLK_OUT1, direction: OUTPUT}
  - {pin_num: '42', peripheral: FlexPWM0, signal: 'A, 1', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, direction: OUTPUT}
  - {pin_num: '43', peripheral: FlexPWM0, signal: 'B, 0', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/PWM0_B0, direction: OUTPUT}
  - {pin_num: '50', peripheral: SWD, signal: SWCLK, pin_signal: P0_1/TCLK/SWCLK/LPUART0_CTS_B/LPSPI0_SDI/CT_INP1}
  - {pin_num: '49', peripheral: SWD, signal: SWDIO, pin_signal: P0_0/TMS/SWDIO/LPUART0_RTS_B/LPSPI0_PCS0/CT_INP0}
  - {pin_num: '51', peripheral: SWD, signal: SWO, pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/I3C0_PUR}
  - {pin_num: '8', peripheral: SYSCON, signal: RESET, pin_signal: P1_29/RESET_B/SPC_LPREQ}
  - {pin_num: '13', peripheral: SUPPLY, signal: VDD, pin_signal: VDD13}
  - {pin_num: '12', peripheral: SUPPLY, signal: VDD_ANA, pin_signal: VDD_ANA/VREFH}
  - {pin_num: '25', peripheral: SUPPLY, signal: VDD_USB, pin_signal: VDD_USB}
  - {pin_num: '12', peripheral: SUPPLY, signal: VREFH, pin_signal: VDD_ANA/VREFH}
  - {pin_num: '11', peripheral: SUPPLY, signal: VREFL, pin_signal: VSS/VSS_ANA/VREFL}
  - {pin_num: '11', peripheral: SUPPLY, signal: VSS, pin_signal: VSS/VSS_ANA/VREFL}
  - {pin_num: '11', peripheral: SUPPLY, signal: VSS_ANA, pin_signal: VSS/VSS_ANA/VREFL}
  - {pin_num: '14', peripheral: LPUART0, signal: RX, pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0}
  - {pin_num: '15', peripheral: LPUART0, signal: TX, pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/CT_INP17/CT2_MAT1/ADC0_A1}
  - {pin_num: '57', peripheral: GPIO1, signal: 'GPIO, 1', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C0_SCL/CT_INP5/CT0_MAT3/ADC0_A17/CMP1_IN3, identifier: ALERT_LED,
    direction: OUTPUT, slew_rate: slow}
  - {pin_num: '58', peripheral: GPIO1, signal: 'GPIO, 2', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C0_SDAS/CT1_MAT0/CT_INP0/ADC0_A18, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: slow}
  - {pin_num: '59', peripheral: GPIO1, signal: 'GPIO, 3', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C0_SCLS/CT1_MAT1/CT_INP1/ADC0_A19/CMP0_IN1, direction: OUTPUT,
    slew_rate: slow}
  - {pin_num: '62', peripheral: GPIO1, signal: 'GPIO, 4', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, direction: INPUT,
    gpio_per_interrupt: kGPIO_InterruptFallingEdge}
  - {pin_num: '63', peripheral: GPIO1, signal: 'GPIO, 5', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '17', peripheral: CTIMER1, signal: 'CAPTURE, 1', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/ADC0_A2/CMP1_IN0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Write to GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* write to INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* Write to PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* Write to PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* Write to PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* Write to PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* LPI2C0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C0_RST_SHIFT_RSTn);
    /* LPUART0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* CTIMER0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER0_RST_SHIFT_RSTn);
    /* CTIMER1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER1_RST_SHIFT_RSTn);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t ALERT_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_1 (pin 57)  */
    GPIO_PinInit(BOARD_INITPINS_ALERT_LED_GPIO, BOARD_INITPINS_ALERT_LED_PIN, &ALERT_LED_config);

    gpio_pin_config_t ONOFF_IMX8MP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO1_2 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_ONOFF_IMX8MP_GPIO, BOARD_INITPINS_ONOFF_IMX8MP_PIN, &ONOFF_IMX8MP_config);

    gpio_pin_config_t CMD_CAMERA_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_3 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_CMD_CAMERA_LED_GPIO, BOARD_INITPINS_CMD_CAMERA_LED_PIN, &CMD_CAMERA_LED_config);

    gpio_pin_config_t ONOFF_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_4 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_ONOFF_INT_GPIO, BOARD_INITPINS_ONOFF_INT_PIN, &ONOFF_INT_config);

    gpio_pin_config_t ONOFF_KILL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO1_5 (pin 63)  */
    GPIO_PinInit(BOARD_INITPINS_ONOFF_KILL_GPIO, BOARD_INITPINS_ONOFF_KILL_PIN, &ONOFF_KILL_config);

    /* Interrupt configuration on GPIO1_4 (pin 62): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITPINS_ONOFF_INT_GPIO, BOARD_INITPINS_ONOFF_INT_PIN, kGPIO_InterruptFallingEdge);
    /* Ctimer input 12 is selected for TIMER0 CAPTSEL 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_CtimerInp12ToTimer0Captsel);
    /* Ctimer input 13 is selected for TIMER1 CAPTSEL 1 */
    INPUTMUX_AttachSignal(INPUTMUX0, 1U, kINPUTMUX_CtimerInp13ToTimer1Captsel);

    PORT0->PCR[0] = ((PORT0->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_0 (pin 49) is configured as SWDIO. */
                     | PORT_PCR_MUX(PORT0_PCR0_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT0->PCR[1] = ((PORT0->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_1 (pin 50) is configured as SWCLK. */
                     | PORT_PCR_MUX(PORT0_PCR1_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_2 (pin 51) is configured as SWO */
    PORT_SetPinMux(PORT0, 2U, kPORT_MuxAlt1);

    PORT0->PCR[2] = ((PORT0->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT1->PCR[1] = ((PORT1->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Slew Rate Enable: Slow. */
                     | PORT_PCR_SRE(PCR_SRE_sre1)

                     /* Pin Multiplex Control: PORT1_1 (pin 57) is configured as P1_1. */
                     | PORT_PCR_MUX(PORT1_PCR1_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_2 (pin 58) is configured as P1_2 */
    PORT_SetPinMux(BOARD_INITPINS_ONOFF_IMX8MP_PORT, BOARD_INITPINS_ONOFF_IMX8MP_PIN, kPORT_MuxAlt0);

    PORT1->PCR[2] = ((PORT1->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_IBE_MASK)))

                     /* Slew Rate Enable: Slow. */
                     | PORT_PCR_SRE(PCR_SRE_sre1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT1->PCR[3] = ((PORT1->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Slew Rate Enable: Slow. */
                     | PORT_PCR_SRE(PCR_SRE_sre1)

                     /* Pin Multiplex Control: PORT1_3 (pin 59) is configured as P1_3. */
                     | PORT_PCR_MUX(PORT1_PCR3_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_4 (pin 62) is configured as P1_4 */
    PORT_SetPinMux(BOARD_INITPINS_ONOFF_INT_PORT, BOARD_INITPINS_ONOFF_INT_PIN, kPORT_MuxAlt0);

    PORT1->PCR[4] = ((PORT1->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_5 (pin 63) is configured as P1_5 */
    PORT_SetPinMux(BOARD_INITPINS_ONOFF_KILL_PORT, BOARD_INITPINS_ONOFF_KILL_PIN, kPORT_MuxAlt0);

    PORT1->PCR[5] = ((PORT1->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_8 (pin 2) is configured as LPI2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SDA_PORT, BOARD_INITPINS_I2C_SDA_PIN, kPORT_MuxAlt3);

    PORT1->PCR[8] = ((PORT1->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_9 (pin 3) is configured as LPI2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SCL_PORT, BOARD_INITPINS_I2C_SCL_PIN, kPORT_MuxAlt3);

    PORT1->PCR[9] = ((PORT1->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[0] = ((PORT2->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_0 (pin 14) is configured as LPUART0_RXD. */
                     | PORT_PCR_MUX(PORT2_PCR0_MUX_mux10)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[1] = ((PORT2->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_1 (pin 15) is configured as LPUART0_TXD. */
                     | PORT_PCR_MUX(PORT2_PCR1_MUX_mux10)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_2 (pin 16) is configured as CT_INP12. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux100)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_3 (pin 17) is configured as CT_INP13 */
    PORT_SetPinMux(BOARD_INITPINS_ENCODER_B_PHA_PORT, BOARD_INITPINS_ENCODER_B_PHA_PIN, kPORT_MuxAlt4);

    PORT2->PCR[3] = ((PORT2->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_6 (pin 20) is configured as ADC0_A3. */
                     | PORT_PCR_MUX(PORT2_PCR6_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT3_6 (pin 44) is configured as PWM0_A0 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_A_PWM_PORT, BOARD_INITPINS_MOTOR_A_PWM_PIN, kPORT_MuxAlt5);

    PORT3->PCR[6] = ((PORT3->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT3->PCR[7] = ((PORT3->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT3_7 (pin 43) is configured as PWM0_B0. */
                     | PORT_PCR_MUX(PORT3_PCR7_MUX_mux101)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_8 (pin 42) is configured as PWM0_A1 */
    PORT_SetPinMux(BOARD_INITPINS_SERVO_PWM_PORT, BOARD_INITPINS_SERVO_PWM_PIN, kPORT_MuxAlt5);

    PORT3->PCR[8] = ((PORT3->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
