/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PCR_SRE_sre1 0x01u          /*!<@brief Slew Rate Enable: Slow */
#define PORT0_PCR0_MUX_mux01 0x01u  /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT0_PCR1_MUX_mux01 0x01u  /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT1_PCR1_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT1_PCR3_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR0_MUX_mux10 0x02u  /*!<@brief Pin Multiplex Control: Alternative 2 (chip-specific) */
#define PORT2_PCR1_MUX_mux10 0x02u  /*!<@brief Pin Multiplex Control: Alternative 2 (chip-specific) */
#define PORT2_PCR2_MUX_mux100 0x04u /*!<@brief Pin Multiplex Control: Alternative 4 (chip-specific) */
#define PORT2_PCR6_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR7_MUX_mux101 0x05u /*!<@brief Pin Multiplex Control: Alternative 5 (chip-specific) */

/*! @name PORT1_9 (number 3), I2C_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SCL_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SCL_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SCL_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_8 (number 2), I2C_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SDA_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SDA_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SDA_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_2 (number 16), ENCODER_A_PHA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ENCODER_A_PHA_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ENCODER_A_PHA_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ENCODER_A_PHA_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_6 (number 20), MESURE_VBAT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MESURE_VBAT_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MESURE_VBAT_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MESURE_VBAT_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_6 (number 44), MOTOR_A_PWM
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_A_PWM_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_A_PWM_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_A_PWM_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_8 (number 42), SERVO_PWM
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SERVO_PWM_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SERVO_PWM_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SERVO_PWM_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_7 (number 43), MOTOR_B_PWM
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_B_PWM_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_B_PWM_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_B_PWM_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT2_0 (number 14), DEBUG_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_RX_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_RX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_RX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_1 (number 15), DEBUG_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_TX_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_TX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_TX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_1 (number 57), ALERT_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ALERT_LED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ALERT_LED_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_ALERT_LED_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ALERT_LED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ALERT_LED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ALERT_LED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ALERT_LED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_2 (number 58), ONOFF_IMX8MP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ONOFF_IMX8MP_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ONOFF_IMX8MP_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_ONOFF_IMX8MP_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ONOFF_IMX8MP_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ONOFF_IMX8MP_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ONOFF_IMX8MP_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ONOFF_IMX8MP_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_3 (number 59), CMD_CAMERA_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CMD_CAMERA_LED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CMD_CAMERA_LED_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_CMD_CAMERA_LED_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_CMD_CAMERA_LED_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CMD_CAMERA_LED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CMD_CAMERA_LED_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CMD_CAMERA_LED_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_4 (number 62), ONOFF_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ONOFF_INT_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ONOFF_INT_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ONOFF_INT_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ONOFF_INT_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ONOFF_INT_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ONOFF_INT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_5 (number 63), ONOFF_KILL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ONOFF_KILL_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ONOFF_KILL_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_ONOFF_KILL_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ONOFF_KILL_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ONOFF_KILL_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ONOFF_KILL_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ONOFF_KILL_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_3 (number 17), ENCODER_B_PHA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ENCODER_B_PHA_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ENCODER_B_PHA_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ENCODER_B_PHA_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
